# Uncomment if you want to produce debugging information for GDB
# ENABLE_GDBINFO_AOBA := 1

# Uncomment if you want to enable assersions
# ENABLE_ASSERT_AOBA := 1

# Uncomment if you want to use OpenCL
# USE_OpenCL_AOBA := 1

# Uncomment if you want to use OpenMP
USE_OpenMP_AOBA := 1

# Specify one of IntelMKL and OpenBLAS
BLAS_AOBA := OpenBLAS

# Uncomment if you need to specify path to OpenBLAS
# OpenBLAS_INC_AOBA := /opt/OpenBLAS/include
# OpenBLAS_LIB_AOBA := /opt/OpenBLAS/lib

# Uncomment if you need to specify path to IntelMKL
# IntelMKL_INC_AOBA := /opt/intel/mkl/include
# IntelMKL_LIB_AOBA := /opt/intel/mkl/lib/intel64
