# Uncomment if you want to produce debugging information for GDB
# ENABLE_GDBINFO := 1

# Uncomment if you want to enable assersions
ENABLE_ASSERT := 0

# Uncomment if you want to use OpenCL
USE_OpenCL := 1

# Uncomment if you want to use OpenMP
USE_OpenMP := 1

# Uncomment if you want to use CuDNN
# USE_CuDNN := 1

# Specify one of IntelMKL and OpenBLAS
BLAS := OpenBLAS

# Uncomment if you need to specify path to OpenBLAS
# OpenBLAS_INC := /opt/OpenBLAS/include
# OpenBLAS_LIB := /opt/OpenBLAS/lib

# Uncomment if you need to specify path to IntelMKL
# IntelMKL_INC := /opt/intel/mkl/include
# IntelMKL_LIB := /opt/intel/mkl/lib/intel64

# Uncomment if you netd to specify path to Cuda Libraries
# CUDA_INC := /usr/local/cuda/include
# CUDA_LIB := /usr/local/cuda/lib64