# Uncomment if you want to produce debugging information for GDB
# ENABLE_GDBINFO_AOBA := 1

# Uncomment if you want to enable assersions
# ENABLE_ASSERT_AOBA := 1

# Uncomment if you want to use OpenCL
USE_OpenCL_AOBA := 1

# Uncomment if you need to specify path to OpenCL development tools
OpenCL_INC_AOBA := /usr/local/cuda/include

# uncomment if you want to use IntelMKL
# USE_CPUBLAS_AOBA := IntelMKL

# Uncomment if you need to specify path to IntelMKL
# IntelMKL_INC_AOBA := /opt/intel/mkl/include
# IntelMKL_LIB_AOBA := /opt/intel/mkl/lib/intel64

# uncomment if you want to use OpenBLAS
USE_CPUBLAS_AOBA := OpenBLAS

# Uncomment if you need to specify path to OpenBLAS
# OpenBLAS_INC_AOBA := /opt/OpenBLAS/include
# OpenBLAS_LIB_AOBA := /opt/OpenBLAS/lib
#OpenBLAS_INC_AOBA := /usr/include/openblas
#OpenBLAS_LIB_AOBA := /usr/lib/openblas

# Uncomment if you want to use
USE_POLICY2187 := 1

